### ISSUE TITLE
exit checks early

### ISSUE THREAD

**Issue by DanielRuf** [mirkoschubert/gdpr-check#14]
The DNS checks and others run multiple regex match tests.
The check should be done after the first hit and `return` in this case or `continue`.
See `getPrefetchingInformation`

**Comment by mirkoschubert** [comment]
You're absolutely right! And as for the DNS checks I already merged your PR.

**Comment by DanielRuf** [comment]
The other checks might need some changes too. This issue is meant as reference for checking the others in the future.

**Comment by mirkoschubert** [comment]
But... I'm planning to swap out those nasty checks for an external solution anyway. Like I did in the new CDN feature (see `getCDNInformation` on `@dev`). I think such descriptive features will be better off in a external file, because it makes it easier to maintain and to add more descriptions in the future.
