### ISSUE TITLE
"Cannot read property 'hasTypekitJS' of undefined" when running just with -f

### ISSUE THREAD

**Issue by DanielRuf** [mirkoschubert/gdpr-check#9]
**Describe the bug**

`--fonts` does not initialize the JSParser as it needs it
**To Reproduce**
```shell
$ node index.js scan example.com -f
fonts
[21:04:54] Checking the URL ...
[21:04:54] Loading HTML file
[21:04:54] Setup additional content
[21:04:54] Loading CSS files

GENERAL INFORMATION

Title:              Example Domain
Description:
URL:                http://example.com/
Software:           Unknown
Cannot read property 'hasTypekitJS' of undefined
```

**Expected behavior**

fonts should be detected
**Screenshots**

**Desktop:**
 - Node Version [e.g. 8.11.2 LTS] 10
 - Version [e.g. 0.3.2] 0.3.4

**Additional context**

**Comment by DanielRuf** [comment]
Overall: the code is unnecessary complicated and hard to understand.

**Comment by mirkoschubert** [comment]
@DanielRuf I can't reproduce this »bug« 😏 
```
› gdpr scan -f example.com                                                                                          gdpr-cli · dev ! 14h25m

[09:05:47] Checking the URL ...
[09:05:47] Loading HTML file
[09:05:47] Setup additional content
[09:05:47] Loading CSS files

GENERAL INFORMATION

Title:              Example Domain
Description:
URL:                http://example.com/
Software:           Unknown

FONTS IMPLEMENTATION

There were no Fonts found.
```
Same versions - on macOS. (And yes, with your `node index.js example.com -f` it's the same...)

Are you sure, you're referring to version `0.3.4`? Because with this version the entire fonts section doesn't rely on the `JSParser` and `CSSParser`  anymore and uses it's own `FontsParser` instead.

I found that the [css](https://www.npmjs.com/package/css) parser I used doesn't work anymore when in a CSS file on the website someone made a mistake (e.g. an `}` too much). And since most of the features don't need a full blown CSS parser (and the handling is much more complicated than now), I wrote my own little parser for the fonts instead.

**Comment by DanielRuf** [comment]
Well, I guess I had 0.3.3 so I think you are right (I thought I upgraded and installed a fresh version as I forked and cloned it directly with the latest changes, will try to rebase and sync with upstream and check again).

Anyway. If there is an issue in between the next commands are aborted as they are not async in most cases (dependent).

**Comment by DanielRuf** [comment]
Ok, synced the remotes locally.

Current findings:
```shell
gdpr/ node index scan
[22:57:42] Checking the URL ...
C:\Users\Daniel\GITHUB\gdpr-cli\lib\tasks.js:581
    url = url.replace(/(https?:)?\/\//, ''); // delete the protocol
              ^

TypeError: Cannot read property 'replace' of undefined
```

missing check for input(s)

Missing warning when `v` and `m` are set.

**Comment by mirkoschubert** [comment]
@DanielRuf Sorry, I didn't see your proposal - I already fixed it `@dev`.
